blog/config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :physicians
  get 'welcome/index'

  resources :parts
  resources :assemblies

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/assembly.rb
class Assembly < ApplicationRecord
  has_and_belongs_to_many :parts
end

blog/app/controllers/assemblies_controller.rb
class AssembliesController < ApplicationController
  before_action :set_assembly, only: [:show, :edit, :update, :destroy]

  # GET /assemblies
  # GET /assemblies.json
  def index
    @assemblies = Assembly.all
  end

  # GET /assemblies/1
  # GET /assemblies/1.json
  def show
  end

  # GET /assemblies/new
  def new
    @assembly = Assembly.new
  end

  # GET /assemblies/1/edit
  def edit
  end

  # POST /assemblies
  # POST /assemblies.json
  def create
    @assembly = Assembly.new(assembly_params)

    respond_to do |format|
      if @assembly.save
        format.html { redirect_to @assembly, notice: 'Assembly was successfully created.' }
        format.json { render :show, status: :created, location: @assembly }
      else
        format.html { render :new }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assemblies/1
  # PATCH/PUT /assemblies/1.json
  def update
    respond_to do |format|
      if @assembly.update(assembly_params)
        format.html { redirect_to @assembly, notice: 'Assembly was successfully updated.' }
        format.json { render :show, status: :ok, location: @assembly }
      else
        format.html { render :edit }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assemblies/1
  # DELETE /assemblies/1.json
  def destroy
    @assembly.destroy
    respond_to do |format|
      format.html { redirect_to assemblies_url, notice: 'Assembly was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assembly
      @assembly = Assembly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assembly_params
      params.require(:assembly).permit(:name, part_ids: [])
    end
end

blog/app/helpers/assemblies_helper.rb
module AssembliesHelper
end

blog/app/views/assemblies/_form.html.erb
<%= form_for(assembly) do |f| %>
  <% if assembly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assembly.errors.count, "error") %> prohibited this assembly from being saved:</h2>

      <ul>
      <% assembly.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parts %>
    <%= f.collection_check_boxes(:part_ids, Part.all, :id, :part_number)  do |b| %>
      <%= b.check_box %>
      <%= b.label %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/assemblies/edit.html.erb
<h1>Editing Assembly</h1>

<%= render 'form', assembly: @assembly %>

<%= link_to 'Show', @assembly %> |
<%= link_to 'Back', assemblies_path %>

blog/app/views/assemblies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assemblies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assemblies.each do |assembly| %>
      <tr>
        <td><%= assembly.name %></td>
        <td><%= link_to 'Show', assembly %></td>
        <td><%= link_to 'Edit', edit_assembly_path(assembly) %></td>
        <td><%= link_to 'Destroy', assembly, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assembly', new_assembly_path %>
<br/>
<br/>
<%= link_to 'Parts', parts_path %>
<br/>
<br/>
<%= link_to 'Main', welcome_index_path %>

blog/app/views/assemblies/new.html.erb
<h1>New Assembly</h1>

<%= render 'form', assembly: @assembly %>

<%= link_to 'Back', assemblies_path %>

blog/app/views/assemblies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @assembly.name %>
</p>

<p>
  <strong>Parts:</strong>
  <ul>
    <% @assembly.parts.each do |part| %>
      <li><%= part.part_number %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_assembly_path(@assembly) %> |
<%= link_to 'Back', assemblies_path %>